version: 2
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    main: ./cmd/docker-lock/main.go
    ldflags:
     - -s -w -X github.com/dockerlocker/docker-lock/cmd/version.Version={{.Version}}
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os}}_
      {{- if eq .Arch "darwin"}}Darwin
      {{- else if eq .Arch "linux"}}Linux
      {{- else if eq .Arch "windows"}}Windows
      {{- else if eq .Arch "amd64"}}x86_64
      {{- else if eq .Arch "386"}}x86_32
      {{- else}}{{ .Arch }}{{end}}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc

